test

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -184,7 +184,8 @@ jobs:
         
         echo "report_url=$decoded_report_url" >> $GITHUB_ENV
     - name: Debug Playwright Log
-      run: cat test-log.txt || echo "Log not found"
+      if: always()
+      run: cat test-log.txt || echo "⚠️ Log file not found"
     - name: Set outcome title
       if: always()
       id: set_outcome_title
